#!/bin/bash

StyleVmessCreate() {
  clear
	echo -e ""
	echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
	echo -e "${Ungu}          ARISCTUNNEL BY POTATO          "
	echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
	echo -e ""
  echo -e "${Ungu}                XRAY VMESS${Suffix}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e ""
  echo -e " VMESS"
  echo -e ""
  echo -e " Remarks       : ${user}"
  echo -e " CITY          : ${city}"
  echo -e " ISP           : ${isp}"
  echo -e " Domain        : ${domain}"
  echo -e " Port TLS      : 443,8443"
  echo -e " Port none TLS : 80,8080"
  echo -e " Port any      : 2052,2053,8880"
  echo -e " id            : ${uuid}"
  echo -e " alterId       : 0"
  echo -e " Security      : auto"
  echo -e " network       : ws,grpc,upgrade"
  echo -e " path ws       : /vmess - /whatever"
  echo -e " serviceName   : vmess"
  echo -e " path upgrade  : /upvmess"
  echo -e ""
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " link TLS          : ${vmesslink1}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"    
  echo -e " link none TLS     : ${vmesslink2}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " link GRPC         : ${vmesslink3}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " link Upgrade TLS  : ${vmesslink4}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " link Upgrade nTLS : ${vmesslink5}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e "${Yellow}         Expired  :  ${exp}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
}

StyleVlessCreate() {
  clear
	echo -e ""
	echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
	echo -e "${Ungu}          ARISCTUNNEL BY POTATO          "
	echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
	echo -e ""
  echo -e "${Ungu}                XRAY VLESS${Suffix}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e ""
  echo -e " VLESS"
  echo -e ""
  echo -e " Remarks       : ${user}"
  echo -e " CITY          : ${city}"
  echo -e " ISP           : ${isp}"
  echo -e " Domain        : ${domain}"
  echo -e " Port TLS      : 443,8443"
  echo -e " Port none TLS : 80,8080"
  echo -e " Port any      : 2052,2053,8880"
  echo -e " id            : ${uuid}"
  echo -e " Encryption    : none"
  echo -e " Network       : ws,grpc,upgrade"
  echo -e " Path ws       : /vless"
  echo -e " serviceName   : vless"
  echo -e " Path upgrade  : /upvless"
  echo -e ""
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " Link TLS         : ${vlesslink1}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " Link none TLS    : ${vlesslink2}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " Link GRPC        : ${vlesslink3}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " Link Upgrade TLS : ${vlesslink4}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " Link Upgrade nTLS: ${vlesslink5}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e "${Yellow}         Expired  :  ${exp}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
}

StyleTrojanCreate() {
  clear
	echo -e ""
	echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
	echo -e "${Ungu}          ARISCTUNNEL BY POTATO          "
	echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
	echo -e ""
  echo -e "${Ungu}                  TROJAN                 ${Suffix}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e ""
  echo -e " TROJAN"
  echo -e ""
  echo -e " Remarks      : ${user}"
  echo -e " CITY         : ${city}"
  echo -e " ISP          : ${isp}"
  echo -e " Domain       : ${domain}"
  echo -e " Port         : 443,8443"
  echo -e " Port any     : 2052,2053,8880"
  echo -e " Key          : ${uuid}"
  echo -e " Network      : ws,grpc,upgrade"
  echo -e " Path ws      : /trojan"
  echo -e " serviceName  : trojan"
  echo -e " Path upgrade : /uptrojan"
  echo -e ""
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " Link WS     : ${trojanlink}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " Link GRPC   : ${trojanlink1}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " Link Upgrade: ${trojanlink2}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e "${Yellow}         Expired  :  ${exp}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
}

StyleSshCreate() {
  clear
	echo -e ""
	echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
	echo -e "${Ungu}          ARISCTUNNEL BY POTATO          "
	echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
	echo -e ""
  echo -e "${Ungu}               SSH/Dropbear            "
  echo -e ""
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " SSH WS        : ${domain}:80@$Login:$Pass"
  echo -e " SSH SSL       : ${domain}:443@$Login:$Pass"
  echo -e " SSH UDP       : ${domain}:1-65535@$Login:$Pass"
  echo -e " SSH SELOWDNS  : ns-${domain}:5300@$Login:$Pass"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  if [[ ${ns} != 'no' && ${pub} != 'no' ]]; then
    echo -e " HOST              : ${domain}"
    echo -e " NameServer        : ${ns}"
    echo -e " Username          : ${Login}"
    echo -e " Password          : ${Pass}"
    echo -e " PUB Key           : ${pub}"
  else
    echo -e " HOST              : ${domain}"
    echo -e " Username          : ${Login}"
    echo -e " Password          : ${Pass}"
  fi
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " TLS               : 443,8443"
  echo -e " None TLS          : 80,8080"
  echo -e " Any               : 2082,2083,8880"
  echo -e " OpenSSH           : 444"
  echo -e " Dropbear          : 90"
  echo -e " SlowDNS           : 53,5300"
  echo -e " UDP-Custom        : 1-65535"
  echo -e " OHP + SSH         : 9080"
  echo -e " Squid Proxy       : 3128"
  echo -e " BadVPN UDPGW      : 7100-7600"
  echo -e " OpenVPN TCP       : 80,1194"
  echo -e " OpenVPN SSL       : 443"
  echo -e " OpenVPN UDP       : 25000"
  echo -e " OpenVPN DNS       : 53"
  echo -e " OHP + OVPN        : 9088"
    echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
    echo -e " Payload WS : GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
echo -e " Payload ENHANCED : PACTH / HTTP/1.1[crlf]Host: [host][crlf]Host: bug.com[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e "${Ungu}                 OpenVPN            "
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e " http://${domain}:81/myvpn-config.zip"
  #ohp_json
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
  echo -e "${Yellow}         Expired  :  ${exp}"
  echo -e "${BlueCyan} ————————————————————————————————————————${Suffix}"
}





